
export const tithiData: Record<number, { np: string; en: string }> = {
  1: { np: "प्रतिपदा", en: "Pratipada" },
  2: { np: "द्वितीया", en: "Dwitiya" },
  3: { np: "तृतीया", en: "Tritiya" },
  4: { np: "चतुर्थी", en: "Chaturthi" },
  5: { np: "पञ्चमी", en: "Panchami" },
  6: { np: "षष्ठी", en: "Sasthi" },
  7: { np: "सप्तमी", en: "Saptami" },
  8: { np: "अष्टमी", en: "Astami" },
  9: { np: "नवमी", en: "Navami" },
  10: { np: "दशमी", en: "Dashami" },
  11: { np: "एकादशी", en: "Ekadashi" },
  12: { np: "द्वादशी", en: "Dwadashi" },
  13: { np: "त्रयोदशी", en: "Trayodashi" },
  14: { np: "चतुर्दशी", en: "Chaturdashi" },
  15: { np: "पूर्णिमा", en: "Purnima" },
  16: { np: "प्रतिपदा", en: "Pratipada" },
  17: { np: "द्वितीया", en: "Dwitiya" },
  18: { np: "तृतीया", en: "Tritiya" },
  19: { np: "चतुर्थी", en: "Chaturthi" },
  20: { np: "पञ्चमी", en: "Panchami" },
  21: { np: "षष्ठी", en: "Sasthi" },
  22: { np: "सप्तमी", en: "Saptami" },
  23: { np: "अष्टमी", en: "Astami" },
  24: { np: "नवमी", en: "Navami" },
  25: { np: "दशमी", en: "Dashami" },
  26: { np: "एकादशी", en: "Ekadashi" },
  27: { np: "द्वादशी", en: "Dwadashi" },
  28: { np: "त्रयोदशी", en: "Trayodashi" },
  29: { np: "चतुर्दशी", en: "Chaturdashi" },
  30: { np: "औंसी", en: "Aaunsi" }
};
